
services:
  - type: web
    name: novo_contratos_cobranca
    env: python
    plan: free
    buildCommand: "pip install -r requirements.txt"
    startCommand: "python app.py"
    disk:
      name: data
      mountPath: /opt/render/project/src/instance
      sizeGB: 1
    envVars:
      - key: PYTHON_VERSION
        value: 3.13.0
