services:
  - type: web
    name: contratos-cobranca
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: python app.py
    autoDeploy: true
    disk:
      name: data
      mountPath: /opt/render/project/src/instance
      sizeGB: 1
